jobs:
  build:
    docker:
      - image: cimg/base:2021.05
    steps:
      - checkout
      - run: sudo add-apt-repository ppa:git-core/ppa
      - run: 
          sudo apt-get install git 
          git --version

