version: 2.1
jobs:
  build:
    docker:
      - image: centos:7
    steps:
      - checkout
      - run: 
          sudo yum install epel-release -y
          sudo yum install dnf -y
          sudo dnf install 'dnf-command(config-manager)' -y
