version: 2.1
jobs:
  build:
    docker:
      - image: centos:7
    steps:
      - checkout
      - run: yum update -y
      - run: yum remove git*
      - run:
          yum install epel-release -y
          yum install dnf -y
      - run:
          rpm -U https://centos7.iuscommunity.org/ius-release.rpm
          yum install git2u
      - run: dnf install 'dnf-command(config-manager)' -y
      - run: dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
      - run: dnf install gh -y
      - run: dnf update gh -y 
      - run: 
          git --version > git.txt
          echo "git version" >> git.txt
          cat git.txt
      #- run: git clone --depth 1 --filter=blob:none --no-checkout https://github.com/vladbielov/csc-release ;
      #- run: cd csc-release
      #- run: git sparse-checkout set changelog
