version: 2.1
jobs:
  build:
    docker:
      - image: centos:7
    steps:
      - checkout
      - run:
          yum install epel-release -y
          yum install dnf -y
      - run: dnf install 'dnf-command(config-manager)' -y
