jobs:
  build:
    docker:
      - image: cimg/base:2021.05
    steps:
      - checkout
      - run: 
          sudo apt-get install git
          git --version
      - run: curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
      - run: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
      - run: sudo apt update
      - run: sudo apt install gh