version: 2.1
jobs:
  build:
    docker:
      - image: centos:7
    steps:
      - checkout
      - run:
          yum install epel-release -y
          yum install dnf -y
      - run: dnf install 'dnf-command(config-manager)' -y
      - run: dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
      - run: dnf install gh -y
      - run: dnf update gh -y 
      - run: git clone --depth 1 --filter=blob:none --sparse https://github.com/vladbielov/csc-release ;
      - run: cd csc-release
      - run: git sparse-checkout set changelog
