jobs:
  build:
    docker:
      - image: cimg/base:2021.05
    steps:
      - checkout
      - run: 
          sudo apt-get install git
          git --version 
          sudo apt install libz-dev libssl-dev libcurl4-gnutls-dev libexpat1-dev gettext cmake gcc   