jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run: 
          sudo apt update
          sudo apt upgrade
      - run: sudo apt install git
          #sudo apt install libz-dev libssl-dev libcurl4-gnutls-dev libexpat1-dev gettext cmake gcc   