jobs:
  build:
    docker:
      - image: cimg/base:2021.05
    steps:
      - checkout
      - run: 
          sudo add-apt-repository -y ppa:git-core/ppa
          sudo apt-get update
          sudo apt-get install git -yn
          #git --version

